#!/bin/bash

set -u
: <<E
$CONSUMER_KEY
$CONSUMER_SECRET
$TOKEN
$TOKEN_SECRET
E

if [[ $? -ne 0 ]]; then
    exit 1
fi
set +u

success=true

# Build images
echo "Building..." >&2
for dir in tweet-api tweet-text-ui tweet-ui; do
    if ! ( cd "$dir" && docker build -t "cttttt/$dir" .; ); then
	success=false
	break
    fi
done

# Teardown
echo "Tearing down..." >&2
{
docker rm -f tweet-api
docker rm -f tweet-text-ui
docker rm -f tweet-ui
docker network rm tweet
} >/dev/null 2>&1

# Start up
echo "Starting up..." >&2

docker network create tweet

docker run \
	-d --name=tweet-api \
	--network=tweet \
	-e "CONSUMER_KEY=$CONSUMER_KEY" \
	-e "CONSUMER_SECRET=$CONSUMER_SECRET" \
	-e "TOKEN=$TOKEN" \
	-e "TOKEN_SECRET=$TOKEN_SECRET" \
	cttttt/tweet-api

docker run \
	-d --name=tweet-text-ui \
	--network=tweet \
	-p 8081:8080 \
	-e "TWEET_API_URL=http://tweet-api:8080/api/tweet" \
	cttttt/tweet-text-ui

docker run \
	-d --name=tweet-ui \
	--network=tweet \
	-p 8082:8080 \
	-e "TWEET_API_URL=http://tweet-api:8080/api/tweet" \
	cttttt/tweet-ui
